export const LOGIN_USER = "LOGIN_USER"
export const SIGN_UP_USER = "SIGN_UP_USER"
export const LOGOUT_USER = "LOGOUT_USER"

export const SUBMIT_POST = "SUBMIT_POST"
export const GET_POSTS = "GET_POSTS"
export const GET_USER_POSTS = "GET_USER_POSTS"
export const EDIT_POST = "EDIT_POST"
export const GET_ONE_POST = "GET_ONE_POST"
export const DELETE_USER_POST = "DELETE_USER_POST"
export const DELETE_POST = "DELETE_POST"
export const DELETE_COMMENT = "DELETE_COMMENT"
export const ADD_COMMENT = "ADD_COMMENT"
export const DELETE_USER_COMMENT = "DELETE_USER_COMMENT"
export const ADD_USER_COMMENT = "ADD_USER_COMMENT"

export const CLEAR_ERROR = "CLEAR_ERROR"
export const ADD_ERROR = "ADD_ERROR"