export const LOGIN_USER = "LOGIN_USER"
export const SIGN_UP_USER = "SIGN_UP_USER"
export const LOGOUT_USER = "LOGOUT_USER"
export const MODAL_SHOW = "MODAL_SHOW"
export const MODAL_HIDE = "MODAL_HIDE"
