export const LOGIN_USER = "LOGIN_USER"
export const SIGN_UP_USER = "SIGN_UP_USER"
export const LOGOUT_USER = "LOGOUT_USER"

export const SUBMIT_POST = "SUBMIT_POST"
export const GET_POSTS = "GET_POSTS"
export const GET_USER_POSTS = "GET_USER_POSTS"
export const EDIT_POST = "EDIT_POST"
export const GET_ONE_POST = "GET_ONE_POST"
export const DELETE_POST = "DELETE_POST"
export const DELETE_COMMENT = "DELETE_COMMENT"